### ISSUE TITLE
dd-agent became defunct and pegged CPU

### ISSUE THREAD

**Issue by TNuzzi** [DataDog/docker-dd-agent#128]
*_Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) *_

```
root@ip-10-11-2-224:~# docker exec dd-agent service datadog-agent info
===================
Collector (v 5.7.4)
===================

  Status date: 2016-09-22 20:54:43 (5s ago)
  Pid: 13
  Platform: Linux-3.13.0-74-generic-x86_64-with-debian-8.4
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: 0.0595 s
    System UTC time: 2016-09-22 20:54:48.873373

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    ec2-hostname: ip-10-11-2-224.ec2.internal
    local-ipv4: 10.11.2.224
    hostname: ip-10-11-2-224
    socket-hostname: ip-10-11-2-224
    local-hostname: ip-10-11-2-224.ec2.internal
    instance-id: i-324a86a1
    socket-fqdn: ip-10-11-2-224

  Checks
  ======

    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check

    disk
    ----
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 1 service check

    docker_daemon
    -------------
      - instance #0 [WARNING]
          Warning: Unable to find any pid directory in /host/proc. If you are running the agent in a container, make sure to share the volume properly: "/proc:/host/proc:ro". See https://github.com/DataDog/docker-dd-agent/blob/master/README.md for more information. Network metrics will be missing
          Warning: Couldn't find pid directory for container: admin,approval,dd-agent,api,jobs,auth,email,logspout,web-redux,web. They'll be missing network metrics
      - Collected 97 metrics, 0 events & 2 service checks


  Emitters
  ========

    - http_emitter [OK]

===================
Dogstatsd (v 5.7.4)
===================

  Status date: 2016-09-22 20:54:43 (5s ago)
  Pid: 33
  Platform: Linux-3.13.0-74-generic-x86_64-with-debian-8.4
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 220
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.7.4)
===================

  Status date: 2016-09-22 20:54:45 (4s ago)
  Pid: 12
  Platform: Linux-3.13.0-74-generic-x86_64-with-debian-8.4
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 0 bytes
  Queue Length: 0
  Flush Count: 773
  Transactions received: 334
  Transactions flushed: 334
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
Seemed to spontaneously happen. We were not issuing any docker daemon actions (was not start/restart/stopping containers).  This happened simultaneously on 2 AWS t2.mediums.  We have been running dd-agent for months with no issues.  The environment is not new and has been running for about a month.

**Describe the results you received:**
From /var/log/datadog/dogstatsd.log:

```
2016-09-22 18:15:59 UTC | ERROR | dd.dogstatsd | dogstatsd(dogstatsd.py:269) | Unable to post payload.
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/dogstatsd.py", line 259, in submit_http
    r = requests.post(url, data=data, timeout=5, headers=headers)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='localhost', port=17123): Read timed out. (read timeout=5)
2016-09-22 18:19:33 UTC | ERROR | dd.dogstatsd | util(util.py:498) | Self-destructing...
2016-09-22 18:20:32 UTC | ERROR | dd.dogstatsd | util(util.py:499) | None
```

**Describe the results you expected:**
To not do this.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is the first time we are seeing this.  The above error message is on both machines that experiencing the CPU spiking issue.

**Comment by hkaj** [comment]
Hi @TNuzzi 
Thank you for the detailed report. This is not an issue we're aware of.

Do you know which process pegged the CPU ? The agent runs a bunch of things: `agent.py` (the collector), `dogstatsd.py`, `jmxfetch.py` if you use the agent to monitor java processes, `ddagent.py` (the forwarder) and `supervisord`.

To help investigate this issue could you also provide the command/manifest you use to start the agent?
And if the issue happens again I suggest you [send us a flare](https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command) from the agent or at least the content of `/var/log/datadog/` so we can see what the agent got stuck on. This error in dogstatsd shouldn't be fatal, and is most likely just a blip.

**Comment by hkaj** [comment]
closing for lack of activity (the conversation might have moved to our support), please reach out if it happens again

**Comment by blast-hardcheese** [comment]
Following up, just encountered this as well. The process pegging was actually dd-agent's bundled supervisord, and the logs were filled with
```
2020-01-15 21:09:20,419 | ERROR | dd.collector | checks.collector(emitter.py:117) | Unable to post payload.
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/emitter.py", line 109, in post_payload
    r = requests.post(url, data=zipped, timeout=5, headers=headers)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=17123): Max retries exceeded with url: /intake/?api_key=<redacted> (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc3803d59d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
The most interesting part of the logs is as follows:
```
root@host# tail -f /mnt/logs/datadog/dogstatsd.log
2020-01-15 19:09:40 PST | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:261) | Flush #55860: flushed 225 metrics, 0 events, and 0 service check runs
2020-01-15 19:09:50 PST | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:261) | Flush #55861: flushed 213 metrics, 0 events, and 0 service check runs
2020-01-15 19:10:00 PST | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:261) | Flush #55862: flushed 213 metrics, 0 events, and 0 service check runs
2020-01-15 19:10:10 PST | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:261) | Flush #55863: flushed 336 metrics, 0 events, and 0 service check runs
2020-01-15 19:10:20 PST | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:261) | Flush #55864: flushed 207 metrics, 0 events, and 0 service check runs
2020-01-15 19:10:30 PST | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:261) | Flush #55865: flushed 201 metrics, 0 events, and 0 service check runs
2020-01-15 19:21:25 PST | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:261) | Flush #55930: flushed 220 metrics, 0 events, and 0 service check runs
2020-01-15 19:25:32 PST | ERROR | dd.dogstatsd | utils.watchdog(watchdog.py:103) | Self-destructing...
2020-01-15 19:27:39 PST | ERROR | dd.dogstatsd | utils.watchdog(watchdog.py:104) | None
```
Whether this is the cause or an effect, it would also be useful to share:
```
2020-01-15 19:27:41 PST | ERROR | dd.collector | checks.collector(unix.py:774) | Cannot compute CPU stats
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/system/unix.py", line 632, in check
    output, _, _ = get_subprocess_output(['mpstat', '1', '3'], self.logger)
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 28, in get_subprocess_output
    proc = subprocess.Popen(command, stdout=stdout_f, stderr=stderr_f)
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 55, in wrapper
    return func(*params, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/opt/datadog-agent/embedded/lib/python2.7/subprocess.py", line 916, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
