### ISSUE TITLE
Restarting docker-dd-agent on boot Centos7, AWS, DC/OS

### ISSUE THREAD

**Issue by hibbert** [DataDog/docker-dd-agent#254]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
# sudo docker exec -it dd-agent /etc/init.d/datadog-agent status
Datadog Agent (supervisor) is running all child processes

# sudo docker exec -it dd-agent /etc/init.d/datadog-agent info -v
2017-11-01 14:43:23,556 | WARNING | dd.collector | utils.service_discovery.config(config.py:31) | No configuration backend provided for service discovery. Only auto config templates will be used.
====================
Collector (v 5.16.0)
====================

  Status date: 2017-11-01 14:43:06 (16s ago)
  Pid: 25
  Platform: Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-debian-8.9
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: 0.0001 s
    System UTC time: 2017-11-01 14:43:23.621358

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    ec2-hostname: ip-10-35-41-17.ec2.internal
    local-ipv4: 10.35.41.17
    socket-hostname: de4e62615af8
    hostname: i-00d4372dfbd6cb7ae
    local-hostname: ip-10-35-41-17.ec2.internal
    instance-id: i-00d4372dfbd6cb7ae
    socket-fqdn: de4e62615af8

  Checks
  ======

    docker_daemon (5.16.0)
    ----------------------
      - instance #0 [OK]
      - Collected 13 metrics, 0 events & 1 service check

    zk (5.16.0)
    -----------
      - instance #0 [ERROR]: ''
        Traceback (most recent call last):
          File "/opt/datadog-agent/agent/checks/__init__.py", line 797, in run
            self.check(copy.deepcopy(instance))
          File "/opt/datadog-agent/agent/checks.d/zk.py", line 143, in check
            ruok_out = self._send_command('ruok', *cx_args)
          File "/opt/datadog-agent/agent/checks.d/zk.py", line 269, in _send_command
            raise ZKConnectionFailure()
        ZKConnectionFailure

      - Collected 3 metrics, 0 events & 1 service check

    ntp (5.16.0)
    ------------
      - Collected 0 metrics, 0 events & 0 service checks

    disk (5.16.0)
    -------------
      - instance #0 [OK]
      - Collected 40 metrics, 0 events & 0 service checks

    mesos_master (5.16.0)
    ---------------------
      - instance #0 [ERROR]: 'Cannot connect to mesos, please check your configuration.'
        Traceback (most recent call last):
          File "/opt/datadog-agent/agent/checks/__init__.py", line 797, in run
            self.check(copy.deepcopy(instance))
          File "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 208, in check
            state_metrics = self._check_leadership(url, timeout, ssl_verify)
          File "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 188, in _check_leadership
            state_metrics = self._get_master_state(url, timeout, verify)
          File "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 175, in _get_master_state
            return self._get_json(url + '/state.json', timeout, verify)
          File "/opt/datadog-agent/agent/checks.d/mesos_master.py", line 167, in _get_json
            raise CheckException("Cannot connect to mesos, please check your configuration.")
        CheckException: Cannot connect to mesos, please check your configuration.

      - Collected 0 metrics, 0 events & 1 service check

    marathon (5.16.0)
    -----------------
      - instance #0 [ERROR]: 'Connection refused when hitting http://leader.mesos:8080/v2/apps'
        Traceback (most recent call last):
          File "/opt/datadog-agent/agent/checks/__init__.py", line 797, in run
            self.check(copy.deepcopy(instance))
          File "/opt/datadog-agent/agent/checks.d/marathon.py", line 63, in check
            response = self.get_json(marathon_path, timeout, auth, acs_url, ssl_verify)
          File "/opt/datadog-agent/agent/checks.d/marathon.py", line 137, in get_json
            raise Exception("Connection refused when hitting %s" % url)
        Exception: Connection refused when hitting http://leader.mesos:8080/v2/apps

      - Collected 0 metrics, 0 events & 1 service check


  Emitters
  ========

    - http_emitter [OK]

====================
Dogstatsd (v 5.16.0)
====================

  Status date: 2017-11-01 14:43:14 (9s ago)
  Pid: 22
  Platform: Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-debian-8.9
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 53
  Packet Count: 901
  Packets per second: 1.7
  Metric count: 9
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.16.0)
====================

  Status date: 2017-11-01 14:43:24 (0s ago)
  Pid: 21
  Platform: Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-debian-8.9
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 0 bytes
  Queue Length: 0
  Flush Count: 187
  Transactions received: 109
  Transactions flushed: 109
  Transactions rejected: 0
  API Key Status: API Key is valid


======================
Trace Agent (v 5.16.0)
======================

  Pid: 20
  Uptime: 544 seconds
  Mem alloc: 2083784 bytes

  Hostname: de4e62615af8
  Receiver: 0.0.0.0:8126
  API Endpoint: https://trace.agent.datadoghq.com

  Bytes received (1 min): 0
  Traces received (1 min): 0
  Spans received (1 min): 0

  Bytes sent (1 min): 0
  Traces sent (1 min): 0
  Stats sent (1 min): 0

Bit from docker inspect

            "Env": [
                "MESOS_MASTER=True",
                "SD_BACKEND=docker",
                "API_KEY=<api_key>",
                "MARATHON_URL=http://leader.mesos:8080",
                "TAGS=dev,mesos-master",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DOCKER_DD_AGENT=yes",
                "AGENT_VERSION=1:5.16.0-1"
            ],
```

**Additional environment details (Operating System, Cloud provider, etc):**
CentOS Linux release 7.3.1611 (Core)
AWS

**Steps to reproduce the issue:**
1. Setup to work with DC/OS, this one is a mesos master (set MESOS_MASTER env to true). Started with restart policy always
```
"RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
```
2. Reboot instance
3. Instance comes back, mesos is backup, can ping leader.mesos on the host but not the container, where it is not resolvable
```
# sudo docker exec -it dd-agent ping leader.mesos
ping: unknown host
```
4. Restart docker instance
5. You are then able to ping

**Describe the results you received:**

See above

**Describe the results you expected:**

I would expect to be able to ping leader.mesos at some point but this just stays down. Is there a better way to ensure the container restarts after a reboot? Supervisord perhaps?

**Comment by hibbert** [comment]
In the end to sort this out I used a systemd unit file and ensured it wouldn't start until leader.mesos could be pinged

``
[Unit]
Description=Datadog Agent
Requires=docker.service
After=docker.service

[Service]
Restart=always
StartLimitInterval=0
RestartSec=5
ExecStartPre=-/usr/bin/docker stop dd-agent
ExecStartPre=-/usr/bin/docker kill dd-agent
ExecStartPre=-/usr/bin/docker rm -f dd-agent
ExecStartPre=/usr/bin/docker pull datadog/docker-dd-agent:11.0.5160
ExecStartPre=/bin/ping -c1 leader.mesos
ExecStart=/bin/bash -c " \
  docker run --name dd-agent \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -v /proc/:/host/proc/:ro \
  -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
  -v /opt/dd-agent-conf.d:/conf.d:ro \
  -v /opt/dd-agent-checks.d:/checks.d:ro \
  -e MARATHON_URL=http://leader.mesos:8080 \
  -e SD_BACKEND=docker \
  -e API_KEY=<api-key> \
  -e MESOS_MASTER=True \
  -e TAGS=dev,mesos-master \
  datadog/docker-dd-agent:11.0.5160"
ExecStop=/usr/bin/docker stop dd-agent

[Install]
WantedBy=multi-user.target
``
