### ISSUE TITLE
Docker_daemon check failed

### ISSUE THREAD

**Issue by gsaxam** [DataDog/docker-dd-agent#265]
I am seeing the following error on the collector logs and metrics are not being reported to datadog.

I have been googling around for a few days now and I see that a lot of people seem to suggest to add `cgroup_enable=memory swapaccount=1` to their grub config as boot parameters on debian boxes. I am on RHEL 6 and read on the docker docs that RHEL does not need the cgroup parameter changes since they are enabled by default. How do I fix this problem?
```
2017-12-07 12:06:57 CST | ERROR | dd.collector | checks.docker_daemon(docker_daemon.py:318) | Docker_daemon check failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 297, in check
    self._process_events(containers_by_id)
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 737, in _process_events
    api_events = self._get_events()
  File "/opt/datadog-agent/agent/checks.d/docker_daemon.py", line 760, in _get_events
    events, changed_container_ids = self.docker_util.get_events()
  File "/opt/datadog-agent/agent/utils/dockerutil.py", line 234, in get_events
    for event in event_generator:
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/docker/client.py", line 268, in _stream_helper
    yield self._result(response, json=decode)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/docker/client.py", line 181, in _result
    return response.json()
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-12-07 12:06:57 CST | WARNING | dd.collector | checks.docker_daemon(__init__.py:699) | Check failed. Will retry at next iteration
```

**Comment by hkaj** [comment]
Hi @gsaxam thanks for reaching out
This is likely a config issue, could you [open a support ticket](https://docs.datadoghq.com/help/) regarding your issue? Our support team will help you solve this.
