### ISSUE TITLE
Check 'docker' instance #0 failed with Docker 1.7

### ISSUE THREAD

**Issue by tj** [DataDog/docker-dd-agent#30]
`datadog/docker-dd-agent:5.4.0` isn't available but I see the releases here

**Comment by tj** [comment]
Also no changelog? does this fix #27? cheers!

**Comment by LotharSee** [comment]
Hi @tj,

Thanks a lot for the heads up! Doing it right now. Latest version is currently `5.4.2`.
Here is the changelog: https://github.com/DataDog/dd-agent/blob/master/CHANGELOG.md

**Comment by tj** [comment]
Hmm tried backport tag again but it seems pretty busted as well with a bunch of:

```
2015-06-22 21:17:01 UTC | ERROR | dd.collector | checks.docker(__init__.py:556) | Check 'docker' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 547, in run
    self.check(copy.deepcopy(instance))
  File "/etc/dd-agent/checks.d/docker.py", line 142, in check
    self._process_events(instance, ids_to_names, skipped_container_ids)
  File "/etc/dd-agent/checks.d/docker.py", line 279, in _process_events
    api_events = self._get_events(instance)
  File "/etc/dd-agent/checks.d/docker.py", line 361, in _get_events
    }, multi=True)
  File "/etc/dd-agent/checks.d/docker.py", line 388, in _get_json
    return json.loads(response)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
JSONDecodeError: Extra data: line 2 column 1 - line 3 column 1 (char 169 - 337)
```

**Comment by tj** [comment]
Ah wow not sure how I missed that hahaha, I'll try 5.4.2

**Comment by LotharSee** [comment]
The build is pending, should be available soon https://registry.hub.docker.com/u/datadog/docker-dd-agent/builds_history/20830/

Also, this looks like a nasty error. Tell me if you get it again with the `5.4.2` tag (with your Docker version).

**Comment by tj** [comment]
hmm still getting it, this is docker 1.7, that might be part of it

**Comment by rbastian** [comment]
We are also seeing the same error with datadog-agent **5.4.2**:

```
2015-06-30 12:50:54 UTC | ERROR | dd.collector | checks.docker(__init__.py:678) | Check 'docker' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 142, in check
    self._process_events(instance, ids_to_names, skipped_container_ids)
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 279, in _process_events
    api_events = self._get_events(instance)
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 363, in _get_events
    }, multi=True)
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 390, in _get_json
    return json.loads(response)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
```

```
root@aws-uw1-dev-platform-11:/var/log/datadog# docker --version
Docker version 1.7.0, build 0baf609
```

```
===================
Collector (v 5.4.2)
===================

  Status date: 2015-06-30 12:53:11 (4s ago)
  Pid: 17109
  Platform: Linux-3.13.0-53-generic-x86_64-with-debian-jessie-sid
  Python Version: 2.7.10
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: -0.0005 s
    System UTC time: 2015-06-30 12:53:16.745944

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    ec2-hostname: ip-xx-xxx-x-xx.us-west-1.compute.internal
    local-ipv4: xx.xxx.x.xx
    hostname: aws-uw1-dev-platform-11
    local-hostname: ip-xx-xxx-x-xx.us-west-1.compute.internal
    instance-id: i-17eaxxdc
    agent-hostname: aws-uw1-dev-platform-11
    socket-fqdn: aws-uw1-dev-platform-11

  Checks
  ======

    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check

    docker
    ------
      - instance #0 [ERROR]: 'Extra data: line 2 column 1 - line 61 column 1 (char 135 - 8055)'
      - Collected 42 metrics, 0 events & 2 service checks

    disk
    ----
      - instance #0 [OK]
      - Collected 36 metrics, 0 events & 1 service check

    network
    -------
      - instance #0 [OK]
      - Collected 111 metrics, 0 events & 1 service check


  Emitters
  ========

    - http_emitter [OK]
```

**Comment by LotharSee** [comment]
Thanks for the detailed report!
That's definitively related to the 1.7.0 release. @hkaj could you try it to see if we can provide a hotfix, then ensure our new check won't break?

**Comment by hkaj** [comment]
sure, I'll look into it asap. Thanks for providing the details @rbastian and @tj !

**Comment by hkaj** [comment]
Hi @tj  and @rbastian, the 5.4.3 that went out a few days ago adds a workaround for this bug, so it should work now.

Thanks for your patience!

**Comment by tj** [comment]
@hkaj nice thanks! what did the check actually affect? Metrics seemed to still be reported correctly

**Comment by hkaj** [comment]
Indeed, the error comes from a bug in the docker events API.
The JSON it returns is invalid. For now the workaround is to return an empty list when we can't decode the json. Some events may be missing because of that.
The next version of the check will use `docker-py` which wraps the docker events in a python generator so we won't need this workaround anymore :)
