### ISSUE TITLE
Can't collect stats from docker through tcp?

### ISSUE THREAD

**Issue by mausch** [DataDog/docker-dd-agent#50]
Is it possible for this container to collect stats from multiple docker hosts?

I'm trying this docker.yaml:

```yaml
init_config:

instances:
  - url: "tcp://develop.docker1.elevate.internal:2375"
    new_tag_names: true
  - url: "tcp://develop.docker2.elevate.internal:2375"
    new_tag_names: true
  - url: "tcp://develop.docker3.elevate.internal:2375"
    new_tag_names: true
```

But this is what I get in /var/log/datadog/collector.log :

```
2015-11-05 17:27:58 UTC | ERROR | dd.collector | checks.docker(__init__.py:689) | Check 'docker' instance #2 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 672, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 140, in check
    containers, ids_to_names = self._get_and_count_containers(instance)
  File "/opt/datadog-agent/agent/checks.d/docker.py", line 175, in _get_and_count_containers
    raise Exception("Failed to collect the list of containers. Exception: {0}".format(e))
Exception: Failed to collect the list of containers. Exception: <urlopen error unknown url type: tcp>
```

I'm probably configuring something incorrectly, but there isn't a lot of documentation in https://app.datadoghq.com/account/settings#integrations/docker .

Cheers,
Mauricio

**Comment by remh** [comment]
Hi @mausch thanks for the feedback.

Cna you try with:
```yaml
url: "http://develop.docker1.elevate.internal:2375"
```
instead ?
It *should* work.

**Comment by mausch** [comment]
Thanks, that worked.
